export const FETCH_MEALS = "FETCH_MEALS";
export const FILTER_MEALS = "FILTER_MEALS";
export const FETCH_MEAL_DETAIL = "FETCH_MEAL_DETAIL";
export const SET_ERRORS = "SET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
