export const FETCH_MEALS = "FETCH_MEALS";
export const FILTER_MEALS = "FILTER_MEALS";
export const FETCH_MEAL_DETAIL = "FETCH_MEAL_DETAIL";

export const FETCH_AUTHORS = "FETCH_AUTHORS";
export const FILTER_AUTHORS = "FILTER_AUTHORS";
export const FETCH_AUTHOR_DETAIL = "FETCH_AUTHOR_DETAIL";
export const SET_AUTHOR_LOADING = "SET_AUTHOR_LOADING";
export const SET_ERRORS = "SET_ERRORS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
